services:
  # 1. Banco de Dados Postgres (Rastreamento do Airflow)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=airflow_user
      - POSTGRES_PASSWORD=AirflowSecurePassword2026!
      - POSTGRES_DB=airflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow_user -d airflow_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Painel Web do Airflow (Interface do Navegador)
  airflow-webserver:
    image: apache/airflow:2.9.1-python3.11
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow_user:AirflowSecurePassword2026!@postgres:5432/airflow_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    ports:
      - "8082:8080"
    command: bash -c "airflow db init && airflow users create --username admin --firstname Fael --lastname Senior --role Admin --email admin@example.com --password admin && airflow webserver"

  # 3. Agendador do Airflow (O coração que vigia o relógio)
  airflow-scheduler:
    image: apache/airflow:2.9.1-python3.11
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow_user:AirflowSecurePassword2026!@postgres:5432/airflow_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: scheduler

volumes:
  postgres_data:
